version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/deploy
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/clean_node_modules.sh
      runas: ubuntu
      timeout: 180
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 600
      runas: ubuntu
