version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/deploy
    owner: root
    group: root
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/clean_node_modules.sh
      runas: ubuntu
    - location: scripts/clean_node_modules.sh
      timeout: 180
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root
