import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactQueryProvider } from './utils/queryProvider';
import { MSWComponent } from './mocks/MSWComponent';
import StyledJsxRegistry from './registry';
import { CookiesProvider } from 'react-cookie';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const enableMSW = process.env.NEXT_PUBLIC_ENABLE_MSW === 'false';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          {enableMSW ? (
            <MSWComponent enableMSW={enableMSW}>{children}</MSWComponent>
          ) : (
            children
          )}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
